import Head from 'next/head'
import dynamic from 'next/dynamic';
import Image from 'next/image';
import Link from 'next/link'
import { useSession, signIn, signOut } from "next-auth/react"

const Map = dynamic(() => import("../components/Map"), { ssr: false });



export default function Home() {

  const { data: session } = useSession()

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
     
      
      <div className="h-full w-full bg-black" >
        <div>
          <h1 className="text-white text-center text-3xl pt-20 font-bold">Welcome to SBK</h1>
          <p className="text-gray-300 text-center pt-5 pb-20">Where you can find your place to DANCE</p>
        </div>        
      </div>

      <div className="">        
        <Image src="/introDance.jpg" layout="responsive" priority="false" width={2158} height={600} />        
      </div>

      <div className="text-center text-2xl pt-8 font-bold" >
            Best Dance places on the city
      </div>
      <div className="pt-5 md:grid md:grid-cols-2 lg:grid-cols-3  mx-auto">          
          <div className="px-10 md:px-5 py-5  mx-auto ">
            <Link href="/map/madrid">
              <a className="">
                <Image className="w-full align-center rounded" src="/madrid.jpg"  width={800} height={600} /> 
                <p className="text-center text-gray-500 text-xl">Madrid</p>
              </a>
            </Link>
          </div>
          <div className="px-10 md:px-5 py-5 mx-auto ">
            <Link href="/map/london">
              <a>
                <Image className="w-full align-center rounded" src="/london.jpg" width={800} height={600} /> 
                <p className="text-center text-gray-500 text-xl">London</p>
              </a>
            </Link>
          </div>
          <div className="px-10 md:px-5 py-5  mx-auto">
            <Link href="/map/berlin">
              <a>
                <Image className="w-full align-center rounded" src="/berlin.jpg"  width={800} height={600} /> 
                <p className="text-center text-gray-500 text-xl">Berlin</p>
              </a>
            </Link>
          </div>
          <div className="px-10 md:px-5 py-5  mx-auto">
            <Link href="/map/barcelona">
              <a>
                <Image className="w-full align-center rounded" src="/barcelona.jpg"  width={800} height={600} /> 
                <p className="text-center text-gray-500 text-xl">Barcelona</p>
              </a>
            </Link>
          </div>
          <div className="px-10 md:px-5 py-5  mx-auto">
            <Link href="/map/edinburgh">
              <a>
                <Image className="w-full align-center rounded" src="/edinburgh.jpg"  width={800} height={600} /> 
                <p className="text-center text-gray-500 text-xl">Edinburgh</p>
              </a>
            </Link>
          </div>
          <div className="px-10 md:px-5 py-5  mx-auto">
            <Link href="/map/porto">
              <a>
                <Image className="w-full align-center rounded" src="/porto.jpg"  width={800} height={600} /> 
                <p className="text-center text-gray-500 text-xl">Porto</p>
              </a>
            </Link>
          </div>
        </div>      
           

      </div>
  )
}
